name: Run contract tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: wildcardsworld/contract-tester:0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app
      - run: yarn
        working-directory: ./app
      - run: yarn coverage
        working-directory: ./app
        env:
          BLOCKCHAIN_NODE_HOST: ganache
